// Monte-Carlo the Fortune-score CDF → data/luckCdf.json (a build step).
//
// "Luckier than X% of all births" is only TRUE if X is S's real position in the
// population. So we roll a big fixed-seed population through the SHARED model,
// score each life, and store the quantile function (a few hundred floats). The
// app loads it and reads percentile = CDF(S) at runtime — O(log n), no sampling.
//
// Re-run whenever the model or the score formula changes:  npm run cdf
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { makeRoller } from '../src/model/roll.js';
import { fortuneScore, buildCdf, percentileOf, tierOf, TIERS, FORTUNE } from '../src/model/score.js';

const __dir = path.dirname(fileURLToPath(import.meta.url));
const load = (f) => JSON.parse(fs.readFileSync(path.join(__dir, '../data', f), 'utf8'));
const SEED = 0x5eed;           // same fixed seed as the sim → reproducible asset
const N = +(process.argv[2] || 200000);
const BUCKETS = 512;

const roller = makeRoller({
  countries: load('countries.json'), params: load('model-params.json'),
  names: load('names.json'), careers: load('careers.json').careers,
  bands: load('bands.json').bands, imputation: load('imputation.json'), seed: SEED,
});

console.log(`\nFortune CDF — N=${N.toLocaleString()} lives, seed=0x${SEED.toString(16)}, ${BUCKETS} buckets`);
const scores = new Array(N);
for (let i = 0; i < N; i++) scores[i] = fortuneScore(roller.rollLife());

const cdf = buildCdf(scores, BUCKETS);
const asset = {
  _note: 'Fortune-score CDF (quantile function). edges[i] = S at cumulative fraction i/buckets. Generated by sim/gen-cdf.mjs; re-run after any model or score change.',
  seed: SEED, n: N, buckets: BUCKETS, weights: FORTUNE.weights,
  edges: cdf.edges.map((x) => +x.toFixed(5)),
};
fs.writeFileSync(path.join(__dir, '../data/luckCdf.json'), JSON.stringify(asset));

// verify: score a FRESH (different-seed) population against the asset → tier
// spread should track the cutoffs (5/20/25/25/15/8/2), with mild sampling noise.
const verifyRoller = makeRoller({
  countries: load('countries.json'), params: load('model-params.json'),
  names: load('names.json'), careers: load('careers.json').careers,
  bands: load('bands.json').bands, imputation: load('imputation.json'), seed: 0xC0FFEE,
});
const M = 30000, counts = {};
let sumP = 0;
for (let i = 0; i < M; i++) {
  const p = percentileOf(fortuneScore(verifyRoller.rollLife()), cdf);
  sumP += p;
  const t = tierOf(p); counts[t.short] = (counts[t.short] || 0) + 1;
}
console.log(`mean percentile ${(sumP / M).toFixed(1)} (expect ~50)\n`);
console.log('TIER SPREAD on a fresh population:');
for (const t of TIERS) {
  const pct = ((counts[t.short] || 0) / M) * 100;
  console.log(`  ${t.short.padEnd(10)} ${pct.toFixed(1).padStart(5)}%`);
}
console.log(`\n→ data/luckCdf.json written (${(JSON.stringify(asset).length / 1024).toFixed(1)} KB)\n`);
